name: Pull Request Labels

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Check for Pull Request Labels
        shell: bash
        run: |
          bin/check_pr_labels "$(gh pr view --json labels ${{ github.event.pull_request.number }})"
